Attaching to django_db_1, django_web_1
[36mdb_1   |[0m ********************************************************************************
[36mdb_1   |[0m WARNING: POSTGRES_HOST_AUTH_METHOD has been set to "trust". This will allow
[36mdb_1   |[0m          anyone with access to the Postgres port to access your database without
[36mdb_1   |[0m          a password, even if POSTGRES_PASSWORD is set. See PostgreSQL
[36mdb_1   |[0m          documentation about "trust":
[36mdb_1   |[0m          https://www.postgresql.org/docs/current/auth-trust.html
[36mdb_1   |[0m          In Docker's default configuration, this is effectively any other
[36mdb_1   |[0m          container on the same system.
[36mdb_1   |[0m 
[36mdb_1   |[0m          It is not recommended to use POSTGRES_HOST_AUTH_METHOD=trust. Replace
[36mdb_1   |[0m          it with "-e POSTGRES_PASSWORD=password" instead to set a password in
[36mdb_1   |[0m          "docker run".
[36mdb_1   |[0m ********************************************************************************
[36mdb_1   |[0m The files belonging to this database system will be owned by user "postgres".
[36mdb_1   |[0m This user must also own the server process.
[36mdb_1   |[0m 
[36mdb_1   |[0m The database cluster will be initialized with locale "en_US.utf8".
[36mdb_1   |[0m The default database encoding has accordingly been set to "UTF8".
[36mdb_1   |[0m The default text search configuration will be set to "english".
[36mdb_1   |[0m 
[36mdb_1   |[0m Data page checksums are disabled.
[36mdb_1   |[0m 
[36mdb_1   |[0m fixing permissions on existing directory /var/lib/postgresql/data ... ok
[36mdb_1   |[0m creating subdirectories ... ok
[36mdb_1   |[0m selecting dynamic shared memory implementation ... posix
[36mdb_1   |[0m selecting default max_connections ... 100
[36mdb_1   |[0m selecting default shared_buffers ... 128MB
[36mdb_1   |[0m selecting default time zone ... Etc/UTC
[36mdb_1   |[0m creating configuration files ... ok
[36mdb_1   |[0m running bootstrap script ... ok
[36mdb_1   |[0m performing post-bootstrap initialization ... ok
[36mdb_1   |[0m initdb: warning: enabling "trust" authentication for local connections
[36mdb_1   |[0m You can change this by editing pg_hba.conf or using the option -A, or
[36mdb_1   |[0m --auth-local and --auth-host, the next time you run initdb.
[36mdb_1   |[0m syncing data to disk ... ok
[36mdb_1   |[0m 
[36mdb_1   |[0m 
[36mdb_1   |[0m Success. You can now start the database server using:
[36mdb_1   |[0m 
[36mdb_1   |[0m     pg_ctl -D /var/lib/postgresql/data -l logfile start
[36mdb_1   |[0m 
[36mdb_1   |[0m waiting for server to start....2020-07-07 22:45:55.780 UTC [48] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
[36mdb_1   |[0m 2020-07-07 22:45:55.781 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
[36mdb_1   |[0m 2020-07-07 22:45:55.795 UTC [49] LOG:  database system was shut down at 2020-07-07 22:45:55 UTC
[36mdb_1   |[0m 2020-07-07 22:45:55.799 UTC [48] LOG:  database system is ready to accept connections
[36mdb_1   |[0m  done
[36mdb_1   |[0m server started
[36mdb_1   |[0m 
[36mdb_1   |[0m /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
[36mdb_1   |[0m 
[36mdb_1   |[0m waiting for server to shut down...2020-07-07 22:45:55.878 UTC [48] LOG:  received fast shutdown request
[36mdb_1   |[0m .2020-07-07 22:45:55.884 UTC [48] LOG:  aborting any active transactions
[36mdb_1   |[0m 2020-07-07 22:45:55.887 UTC [48] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
[36mdb_1   |[0m 2020-07-07 22:45:55.889 UTC [50] LOG:  shutting down
[36mdb_1   |[0m 2020-07-07 22:45:55.912 UTC [48] LOG:  database system is shut down
[36mdb_1   |[0m  done
[36mdb_1   |[0m server stopped
[36mdb_1   |[0m 
[36mdb_1   |[0m PostgreSQL init process complete; ready for start up.
[36mdb_1   |[0m 
[36mdb_1   |[0m 2020-07-07 22:45:56.007 UTC [1] LOG:  starting PostgreSQL 12.3 (Debian 12.3-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
[36mdb_1   |[0m 2020-07-07 22:45:56.007 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
[36mdb_1   |[0m 2020-07-07 22:45:56.007 UTC [1] LOG:  listening on IPv6 address "::", port 5432
[36mdb_1   |[0m 2020-07-07 22:45:56.013 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
[36mdb_1   |[0m 2020-07-07 22:45:56.030 UTC [57] LOG:  database system was shut down at 2020-07-07 22:45:55 UTC
[36mdb_1   |[0m 2020-07-07 22:45:56.035 UTC [1] LOG:  database system is ready to accept connections
[33mweb_1  |[0m Performing system checks...
[33mweb_1  |[0m 
[33mweb_1  |[0m System check identified no issues (0 silenced).
[33mweb_1  |[0m Exception ignored in thread started by: <function check_errors.<locals>.wrapper at 0x7f3457c639d0>
[33mweb_1  |[0m Traceback (most recent call last):
[33mweb_1  |[0m   File "/usr/local/lib/python3.8/site-packages/django/utils/autoreload.py", line 225, in wrapper
[33mweb_1  |[0m     fn(*args, **kwargs)
[33mweb_1  |[0m   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 123, in inner_run
[33mweb_1  |[0m     self.check_migrations()
[33mweb_1  |[0m   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 427, in check_migrations
[33mweb_1  |[0m     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
[33mweb_1  |[0m   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
[33mweb_1  |[0m     self.loader = MigrationLoader(self.connection)
[33mweb_1  |[0m   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 49, in __init__
[33mweb_1  |[0m     self.build_graph()
[33mweb_1  |[0m   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/loader.py", line 206, in build_graph
[33mweb_1  |[0m     self.applied_migrations = recorder.applied_migrations()
[33mweb_1  |[0m   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
[33mweb_1  |[0m     if self.has_table():
[33mweb_1  |[0m   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 44, in has_table
[33mweb_1  |[0m     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
[33mweb_1  |[0m   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 255, in cursor
[33mweb_1  |[0m     return self._cursor()
[33mweb_1  |[0m   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 232, in _cursor
[33mweb_1  |[0m     self.ensure_connection()
[33mweb_1  |[0m   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
[33mweb_1  |[0m     self.connect()
[33mweb_1  |[0m   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
[33mweb_1  |[0m     raise dj_exc_value.with_traceback(traceback) from exc_value
[33mweb_1  |[0m   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
[33mweb_1  |[0m     self.connect()
[33mweb_1  |[0m   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 194, in connect
[33mweb_1  |[0m     self.connection = self.get_new_connection(conn_params)
[33mweb_1  |[0m   File "/usr/local/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 168, in get_new_connection
[33mweb_1  |[0m     connection = Database.connect(**conn_params)
[33mweb_1  |[0m   File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect
[33mweb_1  |[0m     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
[33mweb_1  |[0m django.db.utils.OperationalError: could not translate host name "db" to address: Name or service not known
[33mweb_1  |[0m 
